version: "3"
networks:
  secret-sharing-dev:
    driver: bridge
services:
  app:
    container_name: secret-sharing-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT='Development'
    networks:
      - secret-sharing-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secret-sharing-db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - secret-sharing-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
