version: "3"
networks:
  secret-sharing-dev:
    driver: bridge
services:
  app:
    container_name: deploy-guide
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - secret-sharing-dev
    depends_on:
      - postgres
    volumes:
      - my-wwwroot:/app/wwwroot
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SecreteShar
    ports:
      - "5432:5432"
    networks:
      - secret-sharing-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  my-wwwroot:
    external: false